// GENERATED by scripts/gen-flag-twins.mjs — do not edit by hand.
// Run `npm run gen-flag-twins` to refresh, or `npm run gen-flag-twins -- --check`
// to verify it is up to date. See the script for how these are derived.
//
// Groups of numeric ISO ids whose flag-icons artwork is pixel-identical and that
// are both on the map (so they can actually collide in a flag-only quiz).
export const ARTWORK_TWIN_GROUPS: string[][] = [
  ['36', '334'],
  ['250', '652', '663', '666', '876'],
  ['654', '826'],
];

// One representative of each group above stays guessable (the sovereign / UN
// member); these are the remaining members, which fly the same flag and so are
// marked non-guessable in src/map/world.ts — never a target, never selectable.
export const NON_GUESSABLE_TWIN_IDS: string[] = ['334', '652', '654', '663', '666', '876'];
