// GENERATED by scripts/gen-server-data.mjs — do not edit by hand.
// Mirrors src/game/flagTwins.ts: groups of numeric ISO ids whose flags are
// indistinguishable. Guessing any member of a group counts as correct.

pub static TWIN_GROUPS: &[&[&str]] = &[
    &["36", "334"],
    &["250", "652", "663", "666", "876"],
    &["654", "826"],
    &["360", "492"],
];
