// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DifficultyFilter = { 
/**
 * Allowed continents; empty = all.
 */
continents: Array<string>, 
/**
 * "all" | "small" | "medium" | "large".
 */
size: string, 
/**
 * "un" | "all"; absent treated as "all".
 */
scope?: string | null, };
