// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LeaderboardRow = { nickname: string, avatar: string, score: number, correct: number, rounds: number, 
/**
 * Epoch millis; f64 so it maps to a JS `number` (out of i32 range).
 */
playedAt: number, };
