// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LeaderboardRow = { nickname: string, avatar: string, 
/**
 * Cumulative score across every match this name has played.
 */
score: number, correct: number, rounds: number, 
/**
 * Number of matches this name has finished.
 */
games: number, 
/**
 * Epoch millis of the most recent match; f64 so it maps to a JS `number`.
 */
playedAt: number, };
