// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Player = { id: string, nickname: string, 
/**
 * ISO alpha-2 of the flag used as the avatar.
 */
avatar: string, score: number, connected: boolean, };
