// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomConfig } from "./RoomConfig";

export type RoomInfo = { code: string, config: RoomConfig, hostId: string, };
