// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the public room list returned by `GET /rooms`.
 */
export type RoomSummary = { code: string, host: string, players: number, maxPlayers: number, phase: string, hasPassword: boolean, };
