// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifficultyFilter } from "./DifficultyFilter";

export type RoomConfig = { rounds: number, 
/**
 * Seconds per answer; 0 = no limit (a server cap still applies).
 */
timeLimitSec: number, 
/**
 * Guesses allowed per round before it locks; 1 = single guess.
 */
attempts: number, difficulty: DifficultyFilter, };
