// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoundPlayerResult = { playerId: string, correct: boolean, timeMs: number, points: number, pickedId: string | null, };
