// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalStanding } from "./FinalStanding";
import type { Player } from "./Player";
import type { RoomConfig } from "./RoomConfig";
import type { RoomInfo } from "./RoomInfo";
import type { RoundPlayerResult } from "./RoundPlayerResult";
import type { Standing } from "./Standing";

/**
 * Server -> client messages over the WebSocket.
 */
export type ServerMsg = { "type": "welcome", playerId: string, room: RoomInfo, players: Array<Player>, phase: string, } | { "type": "playerJoined", player: Player, } | { "type": "playerLeft", playerId: string, } | { "type": "kicked" } | { "type": "profileUpdated", playerId: string, nickname: string, avatar: string, } | { "type": "configUpdated", config: RoomConfig, } | { "type": "hostChanged", hostId: string, } | { "type": "countdown", seconds: number, } | { "type": "roundStart", index: number, total: number, alpha2: string, deadlineMs: number, } | { "type": "answerAck", roundIndex: number, accepted: boolean, } | { "type": "scoreboard", standings: Array<Standing>, } | { "type": "roundResult", index: number, targetId: string, results: Array<RoundPlayerResult>, 
/**
 * Pause before the next round (or final results) begins, in ms; the
 * client counts it down so players see the cooldown.
 */
intermissionMs: number, } | { "type": "matchResult", standings: Array<FinalStanding>, winnerId: string | null, } | { "type": "matchAborted" } | { "type": "chat", playerId: string, nickname: string, text: string, } | { "type": "error", code: string, message: string, } | { "type": "pong" };
