// Country metadata (ISO codes, continent, area). Generated by scripts/gen-data.mjs.
import raw from './countries.json';

export interface CountryMeta {
  /** Normalised numeric ISO 3166-1 code (no leading zeros), e.g. "840". */
  id: string;
  /** ISO 3166-1 alpha-2, used for flag SVGs, e.g. "US". */
  alpha2: string;
  /** ISO 3166-1 alpha-3, e.g. "USA". */
  alpha3: string;
  /** Surface area in km². */
  area: number;
  /** Continent / region, e.g. "Europe", "Asia", "Americas". */
  continent: string;
  /** Sub-region, e.g. "Western Europe". */
  subregion: string;
}

export const countries: CountryMeta[] = raw as CountryMeta[];

export const countryById: Map<string, CountryMeta> = new Map(
  countries.map((c) => [c.id, c]),
);

export const CONTINENTS: string[] = Array.from(
  new Set(countries.map((c) => c.continent)),
).sort();

export type SizeBucket = 'small' | 'medium' | 'large';

/** Area thresholds (km²) for the difficulty "by size" filter. */
export const SIZE_THRESHOLDS = { small: 50_000, large: 1_000_000 } as const;

export function sizeBucket(area: number): SizeBucket {
  if (area < SIZE_THRESHOLDS.small) return 'small';
  if (area > SIZE_THRESHOLDS.large) return 'large';
  return 'medium';
}
